### ISSUE TITLE
几点疑问

### ISSUE THREAD

**Issue by CloudFlyCN** [baidu/AdvBox#16]
1. 使用FGSM对Keras模型在CIFAR10数据集攻击时，adversary.is_successful返回时True，用model去predict adversary.adversarial_example也确实被mistake了。但是，show_image_diff时候，Difference是一堆噪点，但是Adversarial Image确跟原始图片差异不大。我特地去看了下生成的对抗样本的RGB值，跟原始图片差距微小，比如“某个像素的某个通道从187变成186.5"，然后我看源码猜测：plt.imshow的时候，图像预处理/255.0差距更小，所以显示不出区别。
其中，使用的attack_config = {"epsilon":0.3,"epsilongs_max":0.5,"epsilon_steps":1,"steps":3}
----------------------------------------
2. 为了对比，我又用了另一个对抗样本攻击repo——cleverhans，也用同样的epsilon=0.3.结果RGB变化很明显，而且它那个调用plt.imshow也可以看出变化。
----------------------------------------
所以，我想请教一下问题出在哪里？

谢谢！

**Comment by duoergun0729** [comment]
你试下乘以256而不是255

**Comment by CloudFlyCN** [comment]
>           你试下乘以256而不是255

是说plt.show预处理的时候除以256吗？效果还是不明显啊。

可否给一个epsilon=0.3的cifar对抗样本例子，我对照一下
