### ISSUE TITLE
关于ebook_mnist_fgsm_pytorch的问题

### ISSUE THREAD

**Issue by wangaxe** [baidu/AdvBox#18]
设置attack_config = {"epsilons": 0.0}时, 攻击的成功率依然为100%

**Comment by duoergun0729** [comment]
FGSM的eps设置一直是和讨厌的事情  所以我在实现的时候做了 优化 当前eps攻击失败 会自动尝试增大eps

**Comment by wangaxe** [comment]
谢谢您的回答,我再看看源码去
