### ISSUE TITLE
python2 tutorial/model.py

### ISSUE THREAD

**Issue by theBuzzyCoder** [baidu/AdvBox#19]
/home/hawk/.local/lib/python2.7/site-packages/paddle/fluid/average.py:63: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)
*** Aborted at 1550691803 (unix time) try "date -d @1550691803" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 2073 (TID 0x7f3f6d781740) from PID 80; stack trace: ***
    @     0x7f3f6d1b5f20 (unknown)
    @     0x7f3f6d574ac8 (unknown)
    @     0x7f3f6d57d0bd (unknown)
    @     0x7f3f6d2de2df _dl_catch_exception
    @     0x7f3f6d57c7ca (unknown)
    @     0x7f3f6d2dd3ad (unknown)
    @     0x7f3f6d2de2df _dl_catch_exception
    @     0x7f3f6d2de36f _dl_catch_error
    @     0x7f3f6d2dd4d9 __libc_dlopen_mode
    @     0x7f3f6d2a8075 (unknown)
    @     0x7f3f6cf67827 __pthread_once_slow
    @     0x7f3f6d2a814f backtrace
    @     0x7f3f6a22dd53 check_callers.part.0
    @     0x7f3f6a22e290 try_binary_elide
    @     0x7f3f6a21646b array_multiply
    @     0x5601403f83c9 (unknown)
    @     0x5601403b736d (unknown)
    @     0x5601403cef58 (unknown)
    @     0x5601403b6a30 (unknown)
    @     0x5601403cef58 (unknown)
    @     0x5601403b6a30 (unknown)
    @     0x5601403cef58 (unknown)
    @     0x5601403b6a30 (unknown)
    @     0x5601403b3d0a (unknown)
    @     0x5601403bbc38 (unknown)
    @     0x5601403b3d0a (unknown)
    @     0x5601403b3629 (unknown)
    @     0x5601403e461f (unknown)
    @     0x5601403df322 (unknown)
    @     0x5601403de67d (unknown)
    @     0x56014038d1ab (unknown)
    @     0x7f3f6d198b97 __libc_start_main

gzip: stdout: Broken pipe
Segmentation fault (core dumped)

**Comment by duoergun0729** [comment]
you can first run mnist_model.py to train model ，then run mnist_tutorial_bim.py.

**Comment by duoergun0729** [comment]
you can first run mnist_model.py to train model ，then run mnist_tutorial_bim.py.
