### ISSUE TITLE
安装后无法运行advbox

### ISSUE THREAD

**Issue by why1988seu** [baidu/AdvBox#2]
你好，我用的ubuntu1604 64位，操作步骤如下：
（1）Anaconda2 5.2.0 64
（2）pip install tensorflow
（3）pip install keras 
（4）pip install paddlepaddle
（5）github拷贝文件到虚拟机（直接下载advbox的zip文件，没用git）
（6）运行tutorials中的cifar10 fgsm文件
报错：
<img width="367" alt="default" src="https://user-images.githubusercontent.com/13652947/45522365-2a56c400-b7f5-11e8-8eb8-2f6cdc995fe8.png">

**Comment by duoergun0729** [comment]
请看我们的示例 "示例2:白盒攻击基于CIFAR10数据集的ResNet模型"
要先运行 python cifar10_model.py 生成模型 再运行python cifar10_tutorial_fgsm.py
