### ISSUE TITLE
请问，win10平台下安装时找不到对应的1.10.1tensorflow版本如何解决？

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [baidu/AdvBox#20]
Collecting tensorflow==1.10.1 (from -r requirements.txt (line 33))
  Could not find a version that satisfies the requirement tensorflow==1.10.1 (from -r requirements.txt (line 33)) (from versions: )
No matching distribution found for tensorflow==1.10.1 (from -r requirements.txt (line 33))

**Comment by duoergun0729** [comment]
高个版本或者低个版本估计也ok  建议还是用linux吧
