### ISSUE TITLE
关于FeatureFqueezingDefence函数

### ISSUE THREAD

**Issue by CloudFlyCN** [baidu/AdvBox#8]
您好! 

最近在做Keras下的FGSM实验，发现KerasModel中有FeatureFqueezingDefence这个函数。

请问，这是表示默认情况下都会加入特征挤压防御嘛？如果只是想得到原始的模型，在KerasModel初始化时，把featurefqueezing_bit_depth设置为None，则scaled_data会跳过下列if语句：

`if self._featurefqueezing_bit_depth is not None:
            #logging.info(data)
            scaled_data=FeatureFqueezingDefence(data.copy(),None,self._featurefqueezing_bit_depth,self._bounds)
            #logging.info(scaled_data)`

进而出现未赋值的情况。

期待回复！谢谢！

**Comment by duoergun0729** [comment]
featurefqueezing_bit_depth featurefqueezing防御算法 提高生成攻击样本的质量 为特征数据的bit位 一般8就ok了 可以看下我的这个文件

**Comment by duoergun0729** [comment]
tutorials/imagenet_tutorial_fgsm_k.py

**Comment by CloudFlyCN** [comment]
感谢这么快的回复！

我之前也按这个加了featurefqueezing_bit_depth=8这个属性，但是在adversary = attack(adversary, **attack_config) 这里抛出了异常，追踪后发现，是发生在feature_squeezing.py文件里的 assert (res <= UB).all() and (res >= LB).all()。

请问，如何解决？谢谢！
